### ISSUE TITLE
Create collection

### ISSUE THREAD

**Issue by dranidis** [Jikkenteki/BGG-PickToPlay#45]
# Acceptance criteria
- [x] Give a unique name to the collection

# Tasks
- [x] Create tests 
- [x] Create code for passing the tests
- [ ] Create the UI
- [ ] Wire the UI elements to the code
